### ISSUE TITLE
[Magic CLI]: warning: unsupported DW_FORM value: 0x1e

### ISSUE THREAD

**Issue by RefinedSoftwareLLC** [modularml/max#222]
### Issue description

When using `magic run mojo file.mojo` I get the following warning but my code runs just fine.

warning: (x86_64) /kaggle/.magic/envs/default/lib/libstdc++.so.6 unsupported DW_FORM value: 0x1e

### Steps to reproduce

os.environ['LD_LIBRARY_PATH'] = f'/kaggle/.magic/envs/default/lib:{os.environ["LD_LIBRARY_PATH"]}'
%alias_magic --cell mojo script -p 'magic --no-progress run mojo'

https://www.kaggle.com/code/michaeldgibson/offline-mojo-template

### Version Info

```shell
Linux x86_64 Ubuntu 20.04.6 LTS
jupyter_client   : 8.6.2
jupyter_core     : 5.7.2
traitlets        : 5.14.3
magic 0.2.3
conda 24.7.1
max 24.4.0 (59977802)
Modular version 24.4.0-59977802-release
mojo 24.4.0 (59977802)
Python 3.11.10
```

**Comment by DWSimmons** [comment]
I was told [here](https://github.com/modularml/max/issues/194) that this would be fixed in the next main release.

**Comment by DWSimmons** [comment]
(zebra) darin@home:/media/darin/M2/magic/zebra$ magic run mojo --version
mojo 24.5.0 (e8aacb95)
(zebra) darin@home:/media/darin/M2/magic/zebra$ magic run mojo
warning: (x86_64) /media/darin/M2/magic/zebra/.magic/envs/default/lib/libstdc++.so.6 unsupported DW_FORM value: 0x1e

**Comment by zbowling** [comment]
This should be fixed now in 24.5!

**Comment by DWSimmons** [comment]
The reason I commented above is that it is still present in 24.5
```(zebra) darin@home:/media/darin/M2/magic/zebra$ magic run mojo --version
mojo 24.5.0 (e8aacb95)
```

**Comment by sibarras** [comment]
Getting the same issue on WSL. It's not fixed. I'm using:
* nighlty mojo 2024.9.1905 (7f82a4e3)
* magic 0.3.0

Error message:
warning: (x86_64) {...}/.magic/envs/default/lib/libstdc++.so.6 unsupported DW_FORM value: 0x1e

Architecture:            x86_64
  CPU op-mode(s):        32-bit, 64-bit
  Address sizes:         46 bits physical, 48 bits virtual
  Byte Order:            Little Endian
CPU(s):                  20
  On-line CPU(s) list:   0-19
Vendor ID:               GenuineIntel
  Model name:            12th Gen Intel(R) Core(TM) i7-12800H

**Comment by ssteinerx** [comment]
And a month later on Linux: 

`mojo 24.5.0 (e8aacb95)`

**Comment by ehsanmok** [comment]
Please try the nightly.
